apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital
  labels:
    app: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
      
  template:
    metadata:
      labels:
        app: hospital
        
    spec:
      containers:
      - name: hospital
      
        image: jeni18/hospital-management-system:hospital
        imagePullPolicy: Always
        ports:
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: hospital-svc
spec:
  selector:
    app: hospital
  ports:
  - port: 80
    targetPort: 8090
